services:
  surikat-wireguard:
    image: linuxserver/wireguard
    container_name: surikat_wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=34.175.100.81
      - SERVERPORT=51900
      - PEERS=jaalvarez2818,alberto,airam,roberto,carlos
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=10.8.0.0/24
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51900:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
    networks:
      - surikat-network

networks:
  surikat-network:
    external: true
